version: "3"

services:
  wtf:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wtf-backend
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_USER: root
      DB_NAME: wtf_development
      DB_PASSWORD: 123456
      DB_HOST: mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
