# Generated by Django 3.1.7 on 2021-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='meals',
            field=models.ManyToManyField(related_name='kitchens', to='meals.Meal'),
        ),
    ]
