# Generated by Django 3.1.7 on 2021-03-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_kitchen_meals'),
    ]

    operations = [
    ]
